#!/bin/bash

source set_common_script_variables.sh

CAIDA_ROUTEVIEWS_SERVER=data.caida.org
CAIDA_DATA_ROUTEVIEWS_DIRECTORY=datasets/routing/routeviews-prefix2as/2009/06
CAIDA_DATA_ROUTEVIEWS_DIRECTORY_URL=http://$CAIDA_ROUTEVIEWS_SERVER/$CAIDA_DATA_ROUTEVIEWS_DIRECTORY
echo $CAIDA_DATA_ROUTEVIEWS_DIRECTORY

wget -P $DATA_DOWNLOAD_DIRECTORY --debug  -N  -A *.gz,*.html -r -l 2 $CAIDA_DATA_ROUTEVIEWS_DIRECTORY_URL --exclude-directories=$CAIDA_DATA_ROUTEVIEWS_DIRECTORY/1,$CAIDA_DATA_ROUTEVIEWS_DIRECTORY/2,$CAIDA_DATA_ROUTEVIEWS_DIRECTORY/3,$CAIDA_DATA_ROUTEVIEWS_DIRECTORY/4,$CAIDA_DATA_ROUTEVIEWS_DIRECTORY/5
find $DATA_DOWNLOAD_DIRECTORY/$CAIDA_ROUTEVIEWS_SERVER -iname 'routeviews-rv2*.pfx2as.*gz' -print0 | xargs -0 ls -tdr | tail -n 1 > $DATA_DOWNLOAD_DIRECTORY/newest_prefix2as_file_name.txt
ln -sf `pwd`/`cat  $DATA_DOWNLOAD_DIRECTORY/newest_prefix2as_file_name.txt` $DATA_DOWNLOAD_DIRECTORY/newest_prefix2as_file.txt